<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           egroups
    integer         irn
    text short      GroupName
    text short      GroupType
    text long       Query
    table           Keys_tab
      integer         Keys
    end
    table           SecDepartment_tab
      text short      SecDepartment
    end
  end
?>
<!-- Data -->
<table name="egroups">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">12631</atom>
    <atom name="GroupName">RP-7953 Surface scans from R.Knigge</atom>
    <atom name="GroupType">Static</atom>
    <atom name="Query"></atom>
    <table name="Keys_tab">
      <tuple>
        <atom name="Keys">2138580</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2138554</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2146145</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2148662</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2148682</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2148688</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2149162</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2149160</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2149161</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2149159</atom>
      </tuple>
      <tuple>
        <atom name="Keys">2149166</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671623</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671624</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671625</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671626</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671627</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671628</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671629</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671630</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671631</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671632</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671633</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671634</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671635</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671636</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671637</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671638</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671639</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671640</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671641</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671642</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671643</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671644</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671645</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671646</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671647</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671648</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671649</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671650</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671651</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671652</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671653</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671654</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671655</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671656</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671657</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671658</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671659</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671660</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671661</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671662</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671663</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671664</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671665</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671666</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671667</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671668</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671669</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671670</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671671</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671672</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671673</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671674</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671675</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671677</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671678</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671679</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671680</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671681</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671682</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671683</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671684</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671685</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671686</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671687</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671688</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671689</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671690</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671691</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671692</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671693</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671694</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671695</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671696</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671697</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671698</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671699</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671700</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671702</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671703</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671704</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671705</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671706</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671707</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671708</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671709</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671710</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671711</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671712</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671713</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671714</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671715</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671716</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671717</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671718</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671719</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671720</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671721</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671722</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671724</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671725</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671726</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671727</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671728</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671729</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671730</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671731</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671732</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671733</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671734</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671735</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671736</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671737</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671738</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671739</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671740</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671741</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671742</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671744</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671745</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671746</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671747</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671748</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671749</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671750</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671751</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671752</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671754</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671755</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671756</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671757</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671758</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671759</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671760</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671761</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671762</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671763</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671764</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671765</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671766</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671767</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671768</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671770</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671771</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671772</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671773</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671774</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671775</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671776</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671777</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671778</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671779</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671780</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671781</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671782</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671783</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671784</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671785</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671786</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671787</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671788</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671789</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671790</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671791</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671792</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671794</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671795</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671796</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671797</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671798</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671799</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671800</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671801</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671803</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671804</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671805</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671806</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671807</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671808</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671809</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671810</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671811</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671812</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671813</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671815</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671816</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671817</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671818</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671819</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671820</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671821</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671822</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671823</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671824</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671825</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671826</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671827</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671828</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671829</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671830</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671831</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671832</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671834</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671835</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671836</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671837</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671838</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671839</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671840</atom>
      </tuple>
    </table>
    <table name="SecDepartment_tab">
      <tuple>
        <atom name="SecDepartment">Technology</atom>
      </tuple>
      <tuple>
        <atom name="SecDepartment">Action</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="irn">5447</atom>
    <atom name="GroupName">RI25 Traveling media</atom>
    <atom name="GroupType">Static</atom>
    <atom name="Query"></atom>
    <table name="Keys_tab">
      <tuple>
        <atom name="Keys">670893</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670894</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670895</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670896</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670897</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670898</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670899</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670900</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670901</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670902</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670903</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670904</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670905</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670906</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670907</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670908</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670909</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670910</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670911</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670912</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670913</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670914</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670915</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670916</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670917</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670918</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670919</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670920</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670921</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670922</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670923</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670924</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670925</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670926</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670927</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670928</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670929</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670930</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670931</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670932</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670933</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670934</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670935</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670936</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670937</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670938</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670939</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670940</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670941</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670942</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670943</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670944</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670945</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670946</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670947</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670948</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670949</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670950</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670951</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670952</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670953</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670954</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670955</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670956</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670957</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670958</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670959</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670960</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670961</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670962</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670963</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670964</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670965</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670966</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670967</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670968</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670969</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670970</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670971</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670972</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670973</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670974</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670975</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670976</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670977</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670978</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670979</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670980</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670981</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670982</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670983</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670984</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670985</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670986</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670987</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670988</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670989</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670990</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670991</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670992</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670993</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670994</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670995</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670996</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670997</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670998</atom>
      </tuple>
      <tuple>
        <atom name="Keys">670999</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671000</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671001</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671002</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671003</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671004</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671005</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671006</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671007</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671008</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671009</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671010</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671011</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671012</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671013</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671014</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671015</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671016</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671017</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671018</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671019</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671020</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671021</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671022</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671023</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671024</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671025</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671026</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671027</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671028</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671029</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671030</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671031</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671032</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671033</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671034</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671035</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671036</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671037</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671038</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671039</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671040</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671041</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671042</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671043</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671044</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671045</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671046</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671047</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671048</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671049</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671050</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671051</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671052</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671053</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671054</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671055</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671056</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671057</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671058</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671059</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671060</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671061</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671062</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671063</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671064</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671065</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671066</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671067</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671068</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671069</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671070</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671071</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671072</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671073</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671074</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671075</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671076</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671077</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671078</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671079</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671080</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671081</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671082</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671083</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671084</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671085</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671086</atom>
      </tuple>
      <tuple>
        <atom name="Keys">671087</atom>
      </tuple>
      <tuple>